import { motion } from "framer-motion";
import { useState } from "react";
import { Leaf, Droplets, Heart, Bug, Sparkles } from "lucide-react";

export default function ImpactVisualization() {
  const [treeCount, setTreeCount] = useState<number>(10);

  // Multipliers based on standard conservation metrics for 1 native tree
  const co2Absorbed = treeCount * 200; // 200 kg of CO2 lifetime
  const waterRetained = treeCount * 5000; // 5000 Liters soil water annually
  const employmentDays = treeCount * 0.12; // 0.12 days of local agriculture jobs
  const biodiversityIndex = Math.ceil(treeCount * 0.25); // 0.25 species supported

  const metrics = [
    {
      id: "co2",
      label: "CO₂ Captured (Lifetime)",
      value: `${co2Absorbed.toLocaleString()} kg`,
      icon: Leaf,
      description: "Direct removal of atmospheric carbon by mature forest structures.",
      color: "text-emerald-400",
      bgGlow: "group-hover:bg-emerald-500/10"
    },
    {
      id: "water",
      label: "Water Retained (Annual)",
      value: `${waterRetained.toLocaleString()} Liters`,
      icon: Droplets,
      description: "Preventing soil runoffs and assisting active aquifer recharge cycles.",
      color: "text-blue-400",
      bgGlow: "group-hover:bg-blue-500/10"
    },
    {
      id: "employment",
      label: "Rural Jobs Created",
      value: treeCount === 0 ? "0 Days" : `${employmentDays.toFixed(1)} Days`,
      icon: Heart,
      description: "Direct livelihood opportunities generated for local planting care.",
      color: "text-rose-400",
      bgGlow: "group-hover:bg-rose-500/10"
    },
    {
      id: "biodiversity",
      label: "Wildlife Families Hosted",
      value: `${biodiversityIndex} Species`,
      icon: Bug,
      description: "Restoring nested canopy ecosystems for bees, local birds, and insects.",
      color: "text-amber-400",
      bgGlow: "group-hover:bg-amber-500/10"
    }
  ];

  return (
    <section className="py-28 relative overflow-hidden bg-[#030712] border-t border-white/5">
      <div className="absolute top-1/2 left-0 -translate-y-1/2 w-96 h-96 bg-emerald-500/5 rounded-full blur-[140px] pointer-events-none" />

      <div className="container mx-auto px-6 relative z-10">
        
        {/* Section Header */}
        <div className="max-w-3xl mx-auto text-center mb-16">
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold uppercase tracking-wider mb-5"
          >
            <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
            Interactive Impact Engine
          </motion.div>
          
          <h2 className="text-4xl md:text-5xl font-black text-white tracking-tight font-serif mb-5">
            Visualize Your Legacy
          </h2>
          <p className="text-neutral-400 font-sans font-light text-base md:text-lg leading-relaxed">
            Drag the interactive slider below to calculate the direct ecological and social returns generated by your chosen contribution level.
          </p>
        </div>

        {/* Dynamic Calculator Box */}
        <div className="max-w-5xl mx-auto glass-card border border-white/5 rounded-3xl p-8 md:p-12 mb-12 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-[100px] pointer-events-none" />

          {/* Slider Row */}
          <div className="flex flex-col items-center text-center pb-10 border-b border-white/5 mb-10">
            <h3 className="text-xs uppercase tracking-widest text-neutral-500 font-bold mb-4">
              Number of Trees Supported
            </h3>

            {/* Tree Number Highlight */}
            <div className="text-6xl md:text-8xl font-black font-serif text-white tracking-tighter flex items-baseline gap-2 mb-8">
              <span>{treeCount}</span>
              <span className="text-2xl font-light text-emerald-400 tracking-wide font-sans">
                {treeCount === 1 ? "Tree" : "Trees"}
              </span>
            </div>

            {/* Sponsorship Cost Quote */}
            <div className="text-sm font-semibold text-neutral-400 mb-6 bg-neutral-900 border border-white/5 px-4 py-2 rounded-full">
              Sponsorship Total: <span className="text-emerald-400">₹{(treeCount * 99).toLocaleString()}</span>
            </div>

            {/* Input Slider */}
            <div className="w-full max-w-2xl relative px-4 flex items-center justify-center">
              <input
                type="range"
                min="1"
                max="250"
                value={treeCount}
                onChange={(e) => setTreeCount(parseInt(e.target.value))}
                className="w-full h-1 bg-neutral-800 rounded-lg appearance-none cursor-pointer accent-emerald-500 focus:outline-none"
              />
              {/* Scale points markers */}
              <div className="absolute bottom-[-24px] left-4 right-4 flex justify-between text-[10px] text-neutral-600 font-bold tracking-widest font-sans pointer-events-none">
                <span>1 TREE</span>
                <span>50 TREES</span>
                <span>100 TREES</span>
                <span>150 TREES</span>
                <span>200 TREES</span>
                <span>250 TREES</span>
              </div>
            </div>
          </div>

          {/* Dynamic Metrics Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {metrics.map((metric) => {
              const Icon = metric.icon;
              return (
                <div
                  key={metric.id}
                  className="group relative p-6 rounded-2xl bg-neutral-950/40 border border-white/5 hover:border-emerald-500/15 transition-all duration-300 flex flex-col justify-between min-h-[200px]"
                >
                  <div>
                    {/* Circle icon */}
                    <div className="w-10 h-10 rounded-xl bg-neutral-900 border border-white/5 flex items-center justify-center text-white mb-4 group-hover:border-emerald-500/20 transition-colors">
                      <Icon className={`w-5 h-5 ${metric.color}`} />
                    </div>

                    {/* Metric Label */}
                    <div className="text-xs text-neutral-400 font-bold uppercase tracking-wider mb-2">
                      {metric.label}
                    </div>
                    
                    {/* Calculation Value */}
                    <div className="text-2xl md:text-3xl font-black font-serif text-white tracking-tight mb-2">
                      {metric.value}
                    </div>
                  </div>

                  {/* Supportive text */}
                  <p className="text-neutral-500 text-xs font-sans font-light leading-relaxed mt-2 border-t border-white/5 pt-2">
                    {metric.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

      </div>
    </section>
  );
}
